"""Banned lexicon and standing copy (FR-010).

The banned-term filter is enforced at template render time (boot-time static
scan, FR-019) and on dynamically generated rationale strings (CI scan). A hit
in shipped copy blocks startup by default; ``COPYLINT_SOFT_FAIL=true``
downgrades boot enforcement to a loud warning for emergency operator use.

Matching is case-insensitive on word boundaries with simple English
inflection expansion, so "dose" also catches "doses"/"dosing" but never
fires inside unrelated words.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

# FR-010: "include but are not limited to" — the core list is verbatim from
# the contract; inflections are generated by _pattern_for below.
BANNED_TERMS: list[str] = [
    "treat",
    "cure",
    "prescribe",
    "dosage",
    "dose",
    "therapy",
    "diagnosis",
    "symptom",
    "relief",
    "benefit",
    "effective for",
    "recommended for",
    "condition",
    "sedating",
    "sedation",
    "alertness",
    "cerebral",
    # Explicit inflections and close variants of the above that a template
    # author might plausibly write (kept literal so random.choice picks a
    # directly detectable string, AC-012).
    "treatment",
    "cures",
    "prescription",
    "therapeutic",
    "diagnose",
    "diagnoses",
    "symptoms",
    "relieve",
    "relieves",
    "benefits",
    "conditions",
    "sedative",
]

_SUFFIXES = ("", "s", "es", "ed", "ing")


def _pattern_for(term: str) -> re.Pattern[str]:
    if " " in term:
        # Multi-word phrase: match verbatim (case-insensitive, whitespace-flexible).
        body = r"\s+".join(re.escape(part) for part in term.split())
        return re.compile(rf"\b{body}\b", re.IGNORECASE)
    return re.compile(
        rf"\b{re.escape(term)}(?:{'|'.join(s for s in _SUFFIXES if s)})?\b",
        re.IGNORECASE,
    )


_PATTERNS: list[tuple[str, re.Pattern[str]]] = [(t, _pattern_for(t)) for t in BANNED_TERMS]


@dataclass(frozen=True)
class LexiconHit:
    term: str
    matched: str
    index: int


def find_banned(text: str) -> list[LexiconHit]:
    """Return all banned-term hits in ``text`` (empty when clean)."""
    hits: list[LexiconHit] = []
    for term, pattern in _PATTERNS:
        for match in pattern.finditer(text):
            hits.append(LexiconHit(term=term, matched=match.group(0), index=match.start()))
    hits.sort(key=lambda h: h.index)
    return hits


def is_clean(text: str) -> bool:
    return not find_banned(text)


# FR-010 standing disclaimer — rendered verbatim on S2, S4 (PDF), and S6.
STANDING_DISCLAIMER = (
    "This placement is a chemistry-derived tendency, not an effect prediction, not medical advice, "
    "and not a guarantee of any experience. The sativa and indica categories are morphological "
    "classifications, not validated chemical or effect categories; the framework is a simplification "
    "of complex chemotype–effect relationships that are not fully established in clinical science. "
    "The weights come from published terpene-effect hypotheses, not clinical trials. Published studies "
    "suggest that strain labels often correlate poorly with chemical composition — which is why this "
    "tool reads chemistry, not labels. Use this placement as one input among many, not as a predictor "
    "of your individual response."
)

# DIS-6(b) degraded-mode notice — visible on the degraded result view and PDF.
DEGRADED_NOTICE = (
    "This placement is based solely on weighted THC-total and CBD-total contributions, which are a "
    "particularly contested basis for directional placement. Terpene data was insufficient for a full placement."
)

# FR-009 display note beside the confidence figures.
CONFIDENCE_NOTE = (
    "Confidence reflects data completeness and a judgment about the published evidence — "
    "not the certainty of your individual experience."
)

# FR-029 display note beside the uncertainty band.
BAND_NOTE = (
    "Band width reflects combined confidence (data completeness and model confidence "
    "assumptions), not measurement precision."
)

# DIS-15 derivation note shown beside derived totals.
DERIVATION_NOTE = "Calculated from THCA + delta-9 THC using the standard 0.877 decarboxylation conversion."
DERIVATION_NOTE_CBD = "Calculated from CBDA + CBD using the standard 0.877 decarboxylation conversion."

# DIS-14 monitored-compound note.
MONITORED_NOTE = "present but not directionally scored pending better literature support"

if not is_clean(STANDING_DISCLAIMER) or not is_clean(DEGRADED_NOTICE):
    raise RuntimeError("standing copy contains a banned term — fix lexicon.py")
